version: '3.8'

services:
#  app:
#    build: .
#    container_name: app
#    ports:
#      - "8080:8080"
#    depends_on:
#      - mongodb
#    environment:
#      MONGO_URI: mongodb://admin:admin123@mongodb:27017/test
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
